"""Initial migration for all application models

Revision ID: c6c36b82a139
Revises: 
Create Date: 2026-08-19 21:51:03.551107

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6c36b82a139'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_drift_reports',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('model_version', sa.String(length=100), nullable=False),
    sa.Column('dataset_drift_score', sa.Float(), nullable=False),
    sa.Column('prediction_drift_score', sa.Float(), nullable=False),
    sa.Column('metrics_payload', sa.JSON(), nullable=True),
    sa.Column('is_drift_detected', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_drift_reports_model_name'), 'model_drift_reports', ['model_name'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('database_connections',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('encrypted_connection_string', sa.Text(), nullable=False),
    sa.Column('host', sa.String(length=255), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('database_name', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('ssl_mode', sa.String(length=50), nullable=False),
    sa.Column('provider', sa.String(length=100), nullable=True),
    sa.Column('permission_status', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_database_connections_user_id'), 'database_connections', ['user_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('connection_id', sa.Uuid(), nullable=True),
    sa.Column('action_type', sa.String(length=100), nullable=False),
    sa.Column('target_entity', sa.String(length=100), nullable=False),
    sa.Column('target_id', sa.String(length=100), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['connection_id'], ['database_connections.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action_type'), 'audit_logs', ['action_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_connection_id'), 'audit_logs', ['connection_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_timestamp'), 'audit_logs', ['timestamp'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('diagnoses',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('connection_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('primary_root_cause', sa.String(length=100), nullable=False),
    sa.Column('contributing_factors', sa.JSON(), nullable=True),
    sa.Column('severity', sa.String(length=50), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('validation_plan', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['connection_id'], ['database_connections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_diagnoses_connection_id'), 'diagnoses', ['connection_id'], unique=False)
    op.create_index(op.f('ix_diagnoses_primary_root_cause'), 'diagnoses', ['primary_root_cause'], unique=False)
    op.create_table('forecast_records',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('connection_id', sa.Uuid(), nullable=False),
    sa.Column('query_id', sa.BigInteger(), nullable=True),
    sa.Column('forecast_window_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('forecast_window_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('degradation_probability', sa.Float(), nullable=False),
    sa.Column('probability_curve', sa.JSON(), nullable=True),
    sa.Column('model_version', sa.String(length=100), nullable=False),
    sa.Column('is_flagged_for_action', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['connection_id'], ['database_connections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_forecast_records_connection_id'), 'forecast_records', ['connection_id'], unique=False)
    op.create_index(op.f('ix_forecast_records_query_id'), 'forecast_records', ['query_id'], unique=False)
    op.create_table('query_metrics',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('connection_id', sa.Uuid(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('db_id', sa.BigInteger(), nullable=True),
    sa.Column('userid', sa.BigInteger(), nullable=True),
    sa.Column('queryid', sa.BigInteger(), nullable=True),
    sa.Column('query_hash', sa.String(length=64), nullable=False),
    sa.Column('query_text', sa.Text(), nullable=True),
    sa.Column('calls', sa.BigInteger(), nullable=False),
    sa.Column('total_exec_time', sa.Float(), nullable=False),
    sa.Column('mean_exec_time', sa.Float(), nullable=False),
    sa.Column('min_exec_time', sa.Float(), nullable=False),
    sa.Column('max_exec_time', sa.Float(), nullable=False),
    sa.Column('rows', sa.BigInteger(), nullable=False),
    sa.Column('shared_blks_hit', sa.BigInteger(), nullable=False),
    sa.Column('shared_blks_read', sa.BigInteger(), nullable=False),
    sa.Column('shared_blks_dirtied', sa.BigInteger(), nullable=False),
    sa.Column('shared_blks_written', sa.BigInteger(), nullable=False),
    sa.Column('temp_blks_read', sa.BigInteger(), nullable=False),
    sa.Column('temp_blks_written', sa.BigInteger(), nullable=False),
    sa.Column('wal_bytes', sa.BigInteger(), nullable=False),
    sa.Column('plans', sa.BigInteger(), nullable=False),
    sa.Column('planning_time', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['connection_id'], ['database_connections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_query_metrics_connection_id'), 'query_metrics', ['connection_id'], unique=False)
    op.create_index(op.f('ix_query_metrics_query_hash'), 'query_metrics', ['query_hash'], unique=False)
    op.create_index(op.f('ix_query_metrics_queryid'), 'query_metrics', ['queryid'], unique=False)
    op.create_index(op.f('ix_query_metrics_timestamp'), 'query_metrics', ['timestamp'], unique=False)
    op.create_table('table_metrics',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('connection_id', sa.Uuid(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('schema_name', sa.String(length=63), nullable=False),
    sa.Column('table_name', sa.String(length=63), nullable=False),
    sa.Column('row_count', sa.BigInteger(), nullable=False),
    sa.Column('table_size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('index_size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('seq_scans', sa.BigInteger(), nullable=False),
    sa.Column('seq_tup_read', sa.BigInteger(), nullable=False),
    sa.Column('idx_scans', sa.BigInteger(), nullable=False),
    sa.Column('idx_tup_fetch', sa.BigInteger(), nullable=False),
    sa.Column('dead_tuples', sa.BigInteger(), nullable=False),
    sa.Column('live_tuples', sa.BigInteger(), nullable=False),
    sa.Column('dead_tuple_ratio', sa.Float(), nullable=False),
    sa.Column('insert_rate', sa.Float(), nullable=False),
    sa.Column('update_rate', sa.Float(), nullable=False),
    sa.Column('delete_rate', sa.Float(), nullable=False),
    sa.Column('last_analyze', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_autoanalyze', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_vacuum', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_autovacuum', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['connection_id'], ['database_connections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_table_metrics_connection_id'), 'table_metrics', ['connection_id'], unique=False)
    op.create_index(op.f('ix_table_metrics_table_name'), 'table_metrics', ['table_name'], unique=False)
    op.create_index(op.f('ix_table_metrics_timestamp'), 'table_metrics', ['timestamp'], unique=False)
    op.create_table('evidence_graph_nodes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('diagnosis_id', sa.Uuid(), nullable=False),
    sa.Column('node_key', sa.String(length=100), nullable=False),
    sa.Column('node_type', sa.String(length=50), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('agent_domain', sa.String(length=50), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('metadata_payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['diagnosis_id'], ['diagnoses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_graph_nodes_diagnosis_id'), 'evidence_graph_nodes', ['diagnosis_id'], unique=False)
    op.create_table('optimization_experiments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('connection_id', sa.Uuid(), nullable=False),
    sa.Column('diagnosis_id', sa.Uuid(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('query_id', sa.BigInteger(), nullable=True),
    sa.Column('table_name', sa.String(length=63), nullable=True),
    sa.Column('strategy', sa.String(length=50), nullable=False),
    sa.Column('candidate_sql', sa.Text(), nullable=False),
    sa.Column('baseline_latency', sa.Float(), nullable=False),
    sa.Column('baseline_p95', sa.Float(), nullable=False),
    sa.Column('baseline_cpu', sa.Float(), nullable=False),
    sa.Column('baseline_io', sa.Float(), nullable=False),
    sa.Column('candidate_latency', sa.Float(), nullable=False),
    sa.Column('candidate_p95', sa.Float(), nullable=False),
    sa.Column('candidate_cpu', sa.Float(), nullable=False),
    sa.Column('candidate_io', sa.Float(), nullable=False),
    sa.Column('predicted_latency_delta', sa.Float(), nullable=False),
    sa.Column('actual_latency_delta', sa.Float(), nullable=True),
    sa.Column('prediction_error', sa.Float(), nullable=True),
    sa.Column('statistical_significance', sa.Boolean(), nullable=False),
    sa.Column('confidence_interval_low', sa.Float(), nullable=True),
    sa.Column('confidence_interval_high', sa.Float(), nullable=True),
    sa.Column('skeptic_findings', sa.JSON(), nullable=True),
    sa.Column('policy_verdict', sa.String(length=50), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('risk', sa.String(length=50), nullable=False),
    sa.Column('rollback', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['connection_id'], ['database_connections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['diagnosis_id'], ['diagnoses.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_optimization_experiments_connection_id'), 'optimization_experiments', ['connection_id'], unique=False)
    op.create_index(op.f('ix_optimization_experiments_diagnosis_id'), 'optimization_experiments', ['diagnosis_id'], unique=False)
    op.create_index(op.f('ix_optimization_experiments_query_id'), 'optimization_experiments', ['query_id'], unique=False)
    op.create_index(op.f('ix_optimization_experiments_timestamp'), 'optimization_experiments', ['timestamp'], unique=False)
    op.create_table('plan_metrics',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('connection_id', sa.Uuid(), nullable=False),
    sa.Column('query_metrics_id', sa.Uuid(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('query_id', sa.BigInteger(), nullable=True),
    sa.Column('plan_hash', sa.String(length=64), nullable=False),
    sa.Column('node_types', sa.JSON(), nullable=True),
    sa.Column('estimated_rows', sa.Float(), nullable=False),
    sa.Column('actual_rows', sa.Float(), nullable=False),
    sa.Column('estimated_cost', sa.Float(), nullable=False),
    sa.Column('actual_time', sa.Float(), nullable=False),
    sa.Column('buffer_hits', sa.BigInteger(), nullable=False),
    sa.Column('buffer_reads', sa.BigInteger(), nullable=False),
    sa.Column('join_types', sa.JSON(), nullable=True),
    sa.Column('parallel_workers', sa.Integer(), nullable=False),
    sa.Column('raw_plan', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['connection_id'], ['database_connections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['query_metrics_id'], ['query_metrics.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plan_metrics_connection_id'), 'plan_metrics', ['connection_id'], unique=False)
    op.create_index(op.f('ix_plan_metrics_plan_hash'), 'plan_metrics', ['plan_hash'], unique=False)
    op.create_index(op.f('ix_plan_metrics_query_id'), 'plan_metrics', ['query_id'], unique=False)
    op.create_index(op.f('ix_plan_metrics_query_metrics_id'), 'plan_metrics', ['query_metrics_id'], unique=False)
    op.create_index(op.f('ix_plan_metrics_timestamp'), 'plan_metrics', ['timestamp'], unique=False)
    op.create_table('approvals',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('experiment_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['experiment_id'], ['optimization_experiments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_approvals_experiment_id'), 'approvals', ['experiment_id'], unique=False)
    op.create_index(op.f('ix_approvals_user_id'), 'approvals', ['user_id'], unique=False)
    op.create_table('bandit_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('experiment_id', sa.Uuid(), nullable=True),
    sa.Column('connection_id', sa.Uuid(), nullable=False),
    sa.Column('context', sa.JSON(), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('propensity', sa.Float(), nullable=False),
    sa.Column('reward', sa.Float(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('model_version', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['connection_id'], ['database_connections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['experiment_id'], ['optimization_experiments.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bandit_events_connection_id'), 'bandit_events', ['connection_id'], unique=False)
    op.create_index(op.f('ix_bandit_events_experiment_id'), 'bandit_events', ['experiment_id'], unique=False)
    op.create_table('canary_runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('experiment_id', sa.Uuid(), nullable=False),
    sa.Column('connection_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('canary_sql_applied', sa.Text(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('observation_window_minutes', sa.Integer(), nullable=False),
    sa.Column('baseline_metrics', sa.JSON(), nullable=True),
    sa.Column('canary_metrics', sa.JSON(), nullable=True),
    sa.Column('rollback_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['connection_id'], ['database_connections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['experiment_id'], ['optimization_experiments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_canary_runs_connection_id'), 'canary_runs', ['connection_id'], unique=False)
    op.create_index(op.f('ix_canary_runs_experiment_id'), 'canary_runs', ['experiment_id'], unique=False)
    op.create_table('evidence_graph_edges',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('diagnosis_id', sa.Uuid(), nullable=False),
    sa.Column('source_node_id', sa.Uuid(), nullable=False),
    sa.Column('target_node_id', sa.Uuid(), nullable=False),
    sa.Column('relation_type', sa.String(length=50), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['diagnosis_id'], ['diagnoses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_node_id'], ['evidence_graph_nodes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_node_id'], ['evidence_graph_nodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_graph_edges_diagnosis_id'), 'evidence_graph_edges', ['diagnosis_id'], unique=False)
    op.create_index(op.f('ix_evidence_graph_edges_source_node_id'), 'evidence_graph_edges', ['source_node_id'], unique=False)
    op.create_index(op.f('ix_evidence_graph_edges_target_node_id'), 'evidence_graph_edges', ['target_node_id'], unique=False)
    op.create_table('model_predictions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('experiment_id', sa.Uuid(), nullable=False),
    sa.Column('model_version', sa.String(length=100), nullable=False),
    sa.Column('prediction', sa.Float(), nullable=False),
    sa.Column('lower_bound', sa.Float(), nullable=False),
    sa.Column('upper_bound', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('actual', sa.Float(), nullable=True),
    sa.Column('absolute_error', sa.Float(), nullable=True),
    sa.Column('features_snapshot', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['experiment_id'], ['optimization_experiments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_predictions_experiment_id'), 'model_predictions', ['experiment_id'], unique=False)
    op.create_table('roi_records',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('experiment_id', sa.Uuid(), nullable=False),
    sa.Column('connection_id', sa.Uuid(), nullable=False),
    sa.Column('estimated_monthly_savings_usd', sa.Float(), nullable=False),
    sa.Column('compute_savings_usd', sa.Float(), nullable=False),
    sa.Column('storage_savings_usd', sa.Float(), nullable=False),
    sa.Column('io_savings_usd', sa.Float(), nullable=False),
    sa.Column('assumed_pricing_tier', sa.String(length=100), nullable=False),
    sa.Column('frequency_per_day', sa.Float(), nullable=False),
    sa.Column('calculation_details', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['connection_id'], ['database_connections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['experiment_id'], ['optimization_experiments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roi_records_connection_id'), 'roi_records', ['connection_id'], unique=False)
    op.create_index(op.f('ix_roi_records_experiment_id'), 'roi_records', ['experiment_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_roi_records_experiment_id'), table_name='roi_records')
    op.drop_index(op.f('ix_roi_records_connection_id'), table_name='roi_records')
    op.drop_table('roi_records')
    op.drop_index(op.f('ix_model_predictions_experiment_id'), table_name='model_predictions')
    op.drop_table('model_predictions')
    op.drop_index(op.f('ix_evidence_graph_edges_target_node_id'), table_name='evidence_graph_edges')
    op.drop_index(op.f('ix_evidence_graph_edges_source_node_id'), table_name='evidence_graph_edges')
    op.drop_index(op.f('ix_evidence_graph_edges_diagnosis_id'), table_name='evidence_graph_edges')
    op.drop_table('evidence_graph_edges')
    op.drop_index(op.f('ix_canary_runs_experiment_id'), table_name='canary_runs')
    op.drop_index(op.f('ix_canary_runs_connection_id'), table_name='canary_runs')
    op.drop_table('canary_runs')
    op.drop_index(op.f('ix_bandit_events_experiment_id'), table_name='bandit_events')
    op.drop_index(op.f('ix_bandit_events_connection_id'), table_name='bandit_events')
    op.drop_table('bandit_events')
    op.drop_index(op.f('ix_approvals_user_id'), table_name='approvals')
    op.drop_index(op.f('ix_approvals_experiment_id'), table_name='approvals')
    op.drop_table('approvals')
    op.drop_index(op.f('ix_plan_metrics_timestamp'), table_name='plan_metrics')
    op.drop_index(op.f('ix_plan_metrics_query_metrics_id'), table_name='plan_metrics')
    op.drop_index(op.f('ix_plan_metrics_query_id'), table_name='plan_metrics')
    op.drop_index(op.f('ix_plan_metrics_plan_hash'), table_name='plan_metrics')
    op.drop_index(op.f('ix_plan_metrics_connection_id'), table_name='plan_metrics')
    op.drop_table('plan_metrics')
    op.drop_index(op.f('ix_optimization_experiments_timestamp'), table_name='optimization_experiments')
    op.drop_index(op.f('ix_optimization_experiments_query_id'), table_name='optimization_experiments')
    op.drop_index(op.f('ix_optimization_experiments_diagnosis_id'), table_name='optimization_experiments')
    op.drop_index(op.f('ix_optimization_experiments_connection_id'), table_name='optimization_experiments')
    op.drop_table('optimization_experiments')
    op.drop_index(op.f('ix_evidence_graph_nodes_diagnosis_id'), table_name='evidence_graph_nodes')
    op.drop_table('evidence_graph_nodes')
    op.drop_index(op.f('ix_table_metrics_timestamp'), table_name='table_metrics')
    op.drop_index(op.f('ix_table_metrics_table_name'), table_name='table_metrics')
    op.drop_index(op.f('ix_table_metrics_connection_id'), table_name='table_metrics')
    op.drop_table('table_metrics')
    op.drop_index(op.f('ix_query_metrics_timestamp'), table_name='query_metrics')
    op.drop_index(op.f('ix_query_metrics_queryid'), table_name='query_metrics')
    op.drop_index(op.f('ix_query_metrics_query_hash'), table_name='query_metrics')
    op.drop_index(op.f('ix_query_metrics_connection_id'), table_name='query_metrics')
    op.drop_table('query_metrics')
    op.drop_index(op.f('ix_forecast_records_query_id'), table_name='forecast_records')
    op.drop_index(op.f('ix_forecast_records_connection_id'), table_name='forecast_records')
    op.drop_table('forecast_records')
    op.drop_index(op.f('ix_diagnoses_primary_root_cause'), table_name='diagnoses')
    op.drop_index(op.f('ix_diagnoses_connection_id'), table_name='diagnoses')
    op.drop_table('diagnoses')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_timestamp'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_connection_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action_type'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_database_connections_user_id'), table_name='database_connections')
    op.drop_table('database_connections')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_model_drift_reports_model_name'), table_name='model_drift_reports')
    op.drop_table('model_drift_reports')
    # ### end Alembic commands ###
